files:
  - source: /app/*.xml
    translation: /build/app/values-%android_code%/%original_file_name%
    translate_attributes: '0'
  - source: /content/*.html
    translation: /build/content/%android_code%/%original_file_name%
  - source: /content/*.properties
    translation: /build/content/%android_code%/%original_file_name%
  - source: /web/*.html
    translation: /build/web/%android_code%/%android_code%
