files:
  - source: /app/*.xml
    translation: /build/app/values-%android_code%/%original_file_name%
    translate_attributes: '0'
  - source: /content/*.html
    translation: /build/content/%locale_with_underscore%/%original_file_name%
  - source: /content/*.properties
    translation: /build/content/%locale_with_underscore%/%original_file_name%
  - source: blocka_app/*.pot
    translation: /build/blocka_app/%file_name%-%locale%.po
  - source: /web/*.html
    translation: /build/web/%two_letters_code%/%original_file_name%
